language: ruby
rvm:
  - 2.6.1
node_js:
  - '8'
cache:
  directories:
    - node_modules
    - /home/travis/.rvm/
install:
  - yarn
script:
  - yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage