language: ruby
rvm:
  - 2.6.1
node_js:
  - '8'
cache:
  directories:
    - node_modules
    - /home/travis/.rvm/
install:
  - yarn
  - yarn global add codecov
  - bundle install
script:
  - yarn test && codecov